### ISSUE TITLE
MySQL settings as Environment Variables

### ISSUE THREAD

**Issue by klara31** [mikenye/docker-flightairmap#1]
Why not make the MySQL server/database/login information available as environment variables, so that an external MySQL server can be used?

**Comment by mikenye** [comment]
You can now optionally use an external MySQL or MariaDB instance. Examples and documentation on how to do this are in the README. 

Please let me know if this works for you!

Thanks for the suggestion.

**Comment by klara31** [comment]
It does not seem to work... The logs indicate:
```
# docker-compose up flightairmap
Pulling flightairmap (mikenye/flightairmap:latest)...
latest: Pulling from mikenye/flightairmap
dc19b8409101: Pull complete
d6f4d918d1ac: Pull complete
c0a8aac06afd: Pull complete
Digest: sha256:5df2abbf3fbad2f36054aa6c064dc527061b92af2c19c5e416823cbfe4f498c8
Status: Downloaded newer image for mikenye/flightairmap:latest
Creating fam ... done
Attaching to fam
fam             | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
fam             | [s6-init] ensuring user provided files have correct perms...exited 0.
fam             | [fix-attrs.d] applying ownership & permissions fixes...
fam             | [fix-attrs.d] done.
fam             | [cont-init.d] executing container initialization scripts...
fam             | [cont-init.d] 01-sanitycheck: executing...
fam             | [cont-init.d] 01-sanitycheck: exited 0.
fam             | [cont-init.d] 02-firstrun: executing...
fam             | mysqlshow: Unknown database 'flightairmap'
fam             |
fam             | New installation detected. Performing first-run tasks...
fam             | This takes a very long time, please be patient!
```
But the database is present on the hostname and with the credentials as listed below in my docker-compose.yml:
```
  flightairmap:
    image: mikenye/flightairmap:latest
    container_name: fam
    ports:
    - 8877:80
    network_mode: bridge
    environment:
    - FAM_BINGKEY=xxx
    - FAM_LATITUDECENTER=x.xxx
    - FAM_LONGITUDECENTER=x.xxx
    - FAM_INSTALLPASSWORD="passord"
    - MYSQLHOSTNAME=192.168.10.3
    - MYSQLDATABASE=flightairmap
    - MYSQLPASSWORD=flight_pass
    - MYSQLUSERNAME=flight
    - BASESTATIONHOST=192.168.10.6
    - FAM_SQUAWK_COUNTRY=NL
    - TZ=${TZ}
    restart: unless-stopped
```
I have already tried to put the parameters between quotes, but no difference.
